### ISSUE TITLE
Sudden logout messages

### ISSUE THREAD

**Issue by Externalizable** [addstar/geSuit#25] opened 2015-04-28 11:20 UTC
Hello!

When a User trys to join the Server, and the Server they're trying to connect to is offline or they're being kicked while logging in, there's just a logout message - not a login message, which confuses the normal Minecraft Player.

**Comment by addstar** [comment] 2015-04-29 00:49
I haven't experienced this, can you paste some proxy/server logs + screenshots? And does it happen every time (ie. can you reproduce it?). We have had times where people try to join a server that is down but I never remember seeing the logout messages. Perhaps some other plugin is causing it.

**Comment by addstar** [comment] 2015-05-19 11:55
Hello,
I finally figured out what was causing this. I discovered the problem while working on another server I was helping out with. The problem occurs when the player joins the proxy but fails to connect to the initial server. For example, if you were to whitelist your initial server (hub/lobby, etc), the player connection would be accepted by bungeecord but rejected by the backend server. There is a check to prevent the player join message from happening until the player actually joins a backend server, but there was no check on the disconnect to make sure they were connected.

We never experienced this issue because we don't use the geSuit join/part messages (we use another system to do that).

This should be fixed now in the latest build (#90) :grin:

**Closed by addstar** 2015-05-19 11:55 UTC
